### ISSUE TITLE
script throws error if all SDS files are present

### ISSUE THREAD

**Issue by thomiczecks** [khoivan88/oe_find_sds-public#34]
Hi,
the script throws an error when all SDS files are present coming from an empty tuple (line 70). I fixed it quick and dirty by changing line 70 into:
```python
val = cursor_select.fetchall()
if not val:
    print('Nothing to download. Exiting!')
    sys.exit()
(to_be_downloaded, ) = zip(*val))
```
Maybe you can come up with a more sophisticated solution.
Cheers,
thomiczecks

**Comment by khoivan88** [comment]
Hi @thomiczecks 

Thank you very much for your catch 😃!

I must admit that it has never occurred to me how my script would handle a database that has all of the SDS.

May I ask if your Open Enventory is set up on Windows with XAMPP or Linux with LAMP stack? A few users using Windows with XAMPP have contacted me about my script not working on that platform. However, i don't have that platform set up so I'm just trying to see if any other users with the same platform for this script to work. 

Again, thank you very much for your catch, it is a great catch 👍!

**Comment by thomiczecks** [comment]
Hi @khoivan88 
I'm running OpenEnventory on an Ubuntu based LAMP stack (actually I'm running LNginxMariadbP), so I can't help you with this :) But I imagine a lot of the problems will come from python on windows handling paths and (back)slashes differently.

**Comment by khoivan88** [comment]
Hi @thomiczecks ,

Yeah, with the help of I user, I was able to narrow it down. Turns out in Windows, with all of my fixes so far, it can query what SDS need to be downloaded, and  download SDS just fine. However, the step of adding the SDS into SQL database is somehow not effective.

Oh well, thank you, anyway. 

I hope you find script(s) useful 😃

**Comment by thomiczecks** [comment]
Hi @khoivan88 
the scripts are awesome, they save me and my coworkers alot of time. I'm currently trying to make them ready for automation so i can update sds and structure completely from commandline (or cron) with the passwords/url/databases as arguments. I'll create a repo when I'm done.

**Comment by khoivan88** [comment]
@thomiczecks ,

I recently set up these scripts (find SDS and find structures) for automation as well. I did use root cronjob with simple `>>` to pipe the command line output into a dated log file. You just needed to turn off the part of the script asking you about root permission and databases, etc. (You have probably already done that). You can either hard code your info (not suggested with password) or use an  `.env` file and a python library like `dot-env`. 

Good luck and please feel free to reach out if you have any issue. 

I wrote some [user guides](open-enventory.gitbook.io) as well. Everyone is welcomed to contribute it send me their written guides to be added into the list.

Best wishes @thomiczecks 😃

**Comment by khoivan88** [comment]
I made the fix [here](https://github.com/khoivan88/oe_find_sds-public/commit/1db87e3668fc93ae0c5137f3a93dfa5ff4ec4c86). Again, thank you very much @thomiczecks  😄

**Comment by thomiczecks** [comment]
I knew there would be a prettier solution 😃. Have a good one!

**Comment by khoivan88** [comment]
@thomiczecks thank you for your kind words. It is 99% your fix. It was good already so I didn't need to do much . 

Also you mentioned search for structures, I have a script for that [here](https://github.com/khoivan88/oe_find_structure). Maybe you already found it

**Comment by thomiczecks** [comment]
already using it 😄. One other question: i noticed that when using a docker LAMP image a "status screen / automatic scroll down screen with infos" appears when populating the database from a file using the import function, but in my own setup it doesn't. It only shows the column select screen until the upload is finished and then shows the mentioned "status screen". Have you ever observed either of those behaviours? Do you know the expected one (and maybe a fix to get there)?

**Comment by khoivan88** [comment]
hmm, interesting observation. I assume you are using the same OE version on those 2 setups?

To be honest,  a few users have mentioned that the import progress screen does not show up until the end of the import process. I couldn't reproduce this issue reliably either but I think it has to do with the server more than the OE. I check the source code and on theory, it should show the progress screen first every single time (which is the expected behavior, unless you import process is super fast, less than a couple of seconds).

Yeah, so, in short, I don't have enough observation data to say when this issue would happen. I think if your server is fast and does not have much `load_average` at the time of the import process, you should expect the normal behavior of showing the status screen first. If somehow, the `load_average` or maybe RAM usage was high, somehow, the server is slow and 'forgets' to serve you the screen ??

I wish I had a better answer 😐

**Comment by thomiczecks** [comment]
mhm interesting. I used the same OE version and the same server (2 identical VMs) and the same test set, so the load shouldn't be the problem. I assumed a missing php package/plugin but wasn't succesful in tracking it down. If I find some time i'll have a look but since it's working in any case it's not a top priority.

**Comment by khoivan88** [comment]
Quite frankly, I have observed normal behavior while users of the same server observed the 'no progress' screen situation and that is why I thought it might depend on the state of the server. 

Regardless, if you used my docker LAMP image, I believe, these are the extra PHP 7.3 packages I installed:
` php php-devel php-gd php-pdo php-soap php-xmlrpc php-xml`

Not sure if it helps 😄 !!

**Comment by thomiczecks** [comment]
thanks. I'll try them out.

**Comment by khoivan88** [comment]
Another possible way to compare those 2 VM instance with regards to PHP environment, I think would be comparing the phpinfo page. OE folder has the `phpinfo.php` page which you can access them with `url-to-your-VM/OE-folder/phpinfo.php`. You can pull this page up for each VM instance and compare them 😄 !
